### ISSUE TITLE
Collect projects using / related to and/or adjacent to ml5

### ISSUE THREAD

**Issue by joeyklee** [ml5js/ml5-website-archive#10]
just to get it started: 

http://mimionuoha.com/a-peoples-guide-to-ai ✅

http://mimionuoha.com/the-library-of-missing-datasets-v-20

https://github.com/yining1023/machine-learning-for-the-web/wiki/References---Inspiration---Links

**Comment by shiffman** [comment]
@AshleyJaneLewis can help with this, she's been compiling a lot of things!

**Comment by joeyklee** [comment]
Excellent! Let's collect all the things!

**Comment by joeyklee** [comment]
Lots of great stuff here:
+ https://github.com/nature-of-code/noc-syllabus-S19/wiki/Final-Projects via @shiffman 

and here:
+ https://github.com/yining1023/machine-learning-for-the-web/wiki/Week-7-2019-Spring

**Comment by shiffman** [comment]
Would it make sense to shuffle the order of the community list each time you go to the page? The other option is to sort by time. Or have one or two manually "featured" projects at the top we curate? It's great the way it is now, just wondering out loud!

**Comment by joeyklee** [comment]
@shiffman  - a few thoughts to add on that:
+ @wenqili - do we have pagination set up at all? I guess at some point the page will get longer and longer
+ We might consider adding a section to the top that has "featured project(s)", then the normal time based list below.

**Comment by joeyklee** [comment]
- training an lstm: https://medium.com/paperspace/training-a-lstm-network-and-sampling-the-resulting-model-in-ml5-js-c48b1d5b46f9
- intro to ml5: https://towardsdatascience.com/introduction-to-ml5-js-3fe51d6a4661
- ml5 and react: https://medium.com/@julienrioux/in-browser-ml-with-react-js-and-ml5-js-f3eeb5149404
- Integrating ml5 and three.js: https://medium.com/@miss.akaplan/integrating-ml5-js-posenet-model-with-three-js-b19710e2862b
- Training pix2pix by @cvalenzuela: https://blog.paperspace.com/generating-interactive-pix2pix-models/
- Training pix2pix by Dongphil: https://medium.com/@dongphilyoo/how-to-train-pix2pix-model-and-generating-on-the-web-with-ml5-js-87d879fb4224

**Comment by bomanimc** [comment]
I believe we have a form submission process for this on the Community page now as well as the awesome-ml5 repository, but tagging @c-dacanay for further comments here before closing this issue!

**Comment by c-dacanay** [comment]
Thanks Bomani! Yup, you're good to close on my end. 

Our community submission form is here: https://forms.gle/18aaSc6J2QbDmLdz6

**Comment by bomanimc** [comment]
Thanks Christina!
