### ISSUE TITLE
Ensure Google Analytics respects Do Not Track

### ISSUE THREAD

**Issue by joeyklee** [ml5js/ml5-website-archive#104]
@wenqili - Thanks for the integration of google analytics. 

We should make sure to integrate the:
* Do Not Track features: https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/#respectdnt
* AnonymizeIP: https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/#anonymize 

I would be in favor of also anonymizing IP addresses for all ml5.js visitors, unless there are other thoughts on how collecting IP addresses will be helpful for us?

**Comment by shiffman** [comment]
Anonymizing IP addresses sounds good to me!

**Comment by joeyklee** [comment]
@wenqili - In addition to adding the google analytics plugin, do we need to add the analytics to the pages of the site? It seems like we haven't yet been getting any data since the transition. Thanks!

**Comment by wenqili** [comment]
@joeyklee @shiffman 
Thanks for the reminder! The settings I did is already anonymized and respect the "DO NOT TRACK".
