### ISSUE TITLE
Change numClasses to numLabels in documentation page

### ISSUE THREAD

**Issue by AndreasRef** [ml5js/ml5-website-archive#107]
[The reference website](https://ml5js.org/reference/api-FeatureExtractor/) still lists `numClasses` as the option to set the number of classes/labels for the FeatureExtractor, but since the update to 3.1 in the library this has been change to `numLabels`.

**Comment by joeyklee** [comment]
Closed with https://github.com/ml5js/ml5-website/pull/110 

Thanks @AndreasRef !

**Comment by joeyklee** [comment]
@all-contributors please add @AndreasRef for issues

**Comment by joeyklee** [comment]
@all-contributors please add @AndreasRef for content
