### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by noisyneuron** [ml5js/ml5-website-archive#116]
There's a few broken links on the website, mostly stuff linking to examples / training tutorials. I've put in my best guess of what the correct URLs are :

---

**Page**: https://ml5js.org/reference/api-KNNClassifier/
**Linked text (in bold)** : *Check out this **example** that uses KNNClassifier to classify data from PoseNet model.*
**Broken URL**: https://ml5js.org/docs/knnclassifier-posenet
**Correct URL**: https://github.com/ml5js/ml5-examples/tree/release/p5js/KNNClassification/KNNClassification_PoseNet

**Page**: https://ml5js.org/reference/api-KNNClassifier/
**Linked text (in bold)** : *Check out this example that uses KNNClassifier to classify data from **PoseNet** model.*
**Broken URL**: https://ml5js.org/docs/PoseNet
**Correct URL**: https://ml5js.org/reference/api-PoseNet/

**Page**: 
https://ml5js.org/reference/api-Word2vec/
**Linked text (in bold)** : *or you can train your own vector models following **this tutorial***
POINT TO https://github.com/ml5js/ml5-data-and-models/tree/master/training
**Correct URL**: https://github.com/ml5js/training-word2vec

**Page**: https://ml5js.org/reference/api-charRNN/
**Linked text (in bold)** : *You can train your own models **using this tutorial** or use this set of pre trained models.*
**Broken URL**: https://ml5js.org/docs/training-lstm
**Correct URL**: https://github.com/ml5js/training-lstm

**Page**: https://ml5js.org/reference/api-charRNN/
**Linked text (in bold)** : ***Here** is a complete example using the p5.js library.*
**Broken URL**: https://github.com/ml5js/ml5-examples/blob/master/p5js/LSTM/LSTM_Text/sketch.js
**Correct URL**: https://github.com/ml5js/ml5-examples/tree/release/p5js/CharRNN/CharRNN_Text

**Page**: https://ml5js.org/reference/api-YOLO/
**Linked text (in bold)** : ***Here** is a complete example.*
**Broken URL**: https://github.com/ml5js/ml5-examples/blob/master/p5js/YOLO/sketch.js
**Correct URL**: https://github.com/ml5js/ml5-examples/tree/release/p5js/YOLO

**Page**: https://ml5js.org/reference/api-SketchRNN/
**Linked text (in bold)** : ***Here** is a complete example.*
**Broken URL**: https://github.com/ml5js/ml5-examples/blob/master/p5js/SketchRNN/sketch.js
**Correct URL**: https://github.com/ml5js/ml5-examples/tree/release/p5js/SketchRNN/SketchRNN_basic

**Page**: https://ml5js.org/reference/api-StyleTransfer/
**Linked text (in bold)** : *you can train your own images following **this tutorial**.*
**Broken URL**: https://ml5js.org/docs/training-styletransfer
**Correct URL**: https://github.com/ml5js/training-styletransfer

**Page**: https://ml5js.org/reference/api-PoseNet/
**Linked text (in bold)** : ***Here** is a complete example.*
**Broken URL**: https://github.com/ml5js/ml5-examples/blob/master/p5js/PoseNet/sketch.js
**Correct URL**: https://github.com/ml5js/ml5-examples/tree/release/p5js/PoseNet/PoseNet_webcam

**Comment by Kaushl2208** [comment]
Hey, I would like to work on it.

**Comment by joeyklee** [comment]
Hi @Kaushl2208 - Thanks so much! Let me know if you have any questions. Otherwise, feel free to make a PR when you're ready.

**Comment by joeyklee** [comment]
Thanks so much @Kaushl2208 - Closing this now with #120
