### ISSUE TITLE
Example cannot load picture in tutorial

### ISSUE THREAD

**Issue by D31F43** [ml5js/ml5-website-archive#122]
Hi,

Recently, I am reviewing the new ml5js website, and find the example linked in the tutorial page causes a failure when loading prediction.

Here is the [link](https://ml5js.org/getting-started/hello-ml5/), at the bottom of the page, there is a [link](https://editor.p5js.org/ml5/sketches/ImageClassification) to p5js web editor. And it will cause an error like this

```
GET https://editor.p5js.org/ml5/sketches/ImageClassification/images/puffin.jpg 404
```

Is it an error of p5 web editor server?

**Comment by bomanimc** [comment]
I think that issues has since been addressed. Thank you for reporting!
