### ISSUE TITLE
Advanced Tab?

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-website-archive#13]
I don't recall specifically what we planned for the "advanced" tab? Is this a tab for if there is info about how to train your own model with python? I think we should avoid the word "advanced". Maybe just some pages would have a "training" tab?

**Comment by wenqili** [comment]
I guess the ”advanced” is a place holder text on the design sketch. I changed it to ”training” tab

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wenqili** [comment]
I turned the "advanced tab" into a `training tab` and it will automatically hide when there is no content
