### ISSUE TITLE
bodyPix documentation example mistake

### ISSUE THREAD

**Issue by mrbombmusic** [ml5js/ml5-website-archive#140]
In the basic example for bodyPix in the documentation, the callback function in bodypix.segment is called gotResults. However, the function underneath which logs the results is called gotImage. I assume the name of the callback should be the same as the function which logs the results. 
![Screenshot 2019-11-27 21 56 11](https://user-images.githubusercontent.com/26189509/69773704-8e974680-1161-11ea-8af9-6dd532df422b.png)

**Comment by bomanimc** [comment]
Thanks for opening this @mrbombmusic (also hello!). This issue was addressed in https://github.com/ml5js/ml5-library/pull/753 and is fixed now!
