### ISSUE TITLE
Scroll position doesn't reset after page transitions

### ISSUE THREAD

**Issue by bomanimc** [ml5js/ml5-website-archive#146]
### Issue
The scroll position doesn't reset after page transitions.

### Expectation
After scrolling down on a page and visiting another page, the user begins the new page from the top.

### Reproducible Example
Visit the reference page for the [DCGAN model](https://learn.ml5js.org/docs/#/reference/dcgan) and scroll down to the bottom of the page. Next, visit the reference page for another model, such as SketchRNN by selecting it from the left-hand sidebar. Notice that the SketchRNN route is loaded, but you are at the bottom of the page, requiring you to scroll back to the top of the page to see the initial content.

**Comment by bomanimc** [comment]
Closing this issue on this repository, as this actually has to do with the Docsify setup. I'll open this issue on ml5-library where that configuration lives.

**Comment by joeyklee** [comment]
Hi @bomanimc ! Thanks! I will follow up accordingly. This is great feedback!
