### ISSUE TITLE
Tutorial Tabs

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-website-archive#15]
For now, on some pages we can add any videos from here:

https://www.youtube.com/playlist?list=PLRqwX-V7Uu6YPSwT06y_AEYTqIwbeam3y

There are also some videos for `StyleTransfer` and `chaRNN` in this playlist.

https://www.youtube.com/playlist?list=PLRqwX-V7Uu6Y6kSfxOjq5zk4gkDK8q_n1

I plan to make more videos over the summer, but by no means does the material on these pages need to be limited to coding train videos!!

@yining1023 may also have some materials from her class that could go on the tutorials page!

I think a question is whether there's a written tutorial on the tab or if the page is more of a collection of links outward?

For now I suppose we embed the videos since that is what we have?

**Comment by bomanimc** [comment]
@shiffman checking in: is this something that you're still considering, or has adding links to tutorials in the docs mostly addressed this issue?

**Comment by shiffman** [comment]
I'm good with our current system of adding the tutorial videos to the reference page themselves! I'll note I also maintain my own pages for these tutorial videos in case any code links or other references is useful.

https://thecodingtrain.com/learning/ml5/

Feel free to close if there isn't anything else needed from me!

**Comment by bomanimc** [comment]
Thanks! Sounds good!
