### ISSUE TITLE
"Models"?

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-website-archive#16]
Though it fits for many items on the list, I don't think "models" is the right umbrella term for the list of ml5 functions.

<img width="392" alt="Screen Shot 2019-05-09 at 7 41 25 AM" src="https://user-images.githubusercontent.com/191758/57462584-f4f06200-722d-11e9-835a-cbe62ce01e1e.png">

The thing is I don't have a better idea! What these are more literally are "ml5 functions" "ml5 features". Features isn't good b/c it means something specific in ML. Would it be terrible to just not have a heading? But instead of organize the sidebar list into categories?

Or anyone have an idea?

**Comment by yining1023** [comment]
"ml5 functions", "ml5 methods", "ml5 API reference"?
"functions" might be the easy one to understand.

**Comment by joeyklee** [comment]
@yining1023 - I like:
1.  ml5 API reference
2. ml5 methods
3. ml5 services (?)
4. ml5 utilities (?)
5. ml5 operations (?)

**Comment by joeyklee** [comment]
For now, I've just changed the heading to `Reference` in https://github.com/ml5js/ml5-website-2/pull/17/commits/7b04f6be6e257ebb2d45d8e06e7e235e8e12546b ==> we can change this later to be more specific as desired/needed :)

**Comment by joeyklee** [comment]
Closing this for now. We can revisit this in the next iteration of the site. Thanks!
