### ISSUE TITLE
Links to "getting started" and "docs" on homepage are not working - they don't point to the right page

### ISSUE THREAD

**Issue by jasikpark** [ml5js/ml5-website-archive#164]

**Comment by joeyklee** [comment]
Hi @jasikpark - ah! you're right. That entire nav bar is broken. We recently migrated our docs to a different host and seems like this is a result of that. We will update this! Thanks for pointing this out. 

cc/ @bomanimc

**Comment by bomanimc** [comment]
Thanks for the heads up @jasikpark! Yep, I moved our docs to Netlify yesterday and I forgot to remove all references to the base GitHub Pages domain. This PR corrected the issue: https://github.com/ml5js/ml5-library/pull/1058. 

Thanks for flagging!

**Comment by jasikpark** [comment]
Oh lmao nice
