### ISSUE TITLE
Getting Started (p5.js web editor)

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-website-archive#32]
The Getting Started page has a nice summary of how to work with ml5 without p5.js. I was thinking that adding a short section about working with p5.js and link to a blank ml5.js sketch "template" and/or the same "image classification" example in the p5.js editor is a quicker, simpler path to getting started!

**Comment by wenqili** [comment]
It's totally doable and I think iframe could work very well here. 
I added a "responsive helper" to help embed responsive iframes:
```html
<!-- wrap the youtube embed code with <div class="iframe__container"></div> !-->
<!-- example !-->
<div class="iframe__container iframe__container--video">
  <iframe src="URL to iframe" frameborder="0" allowfullscreen> 
  </iframe>
</div>
```

**Comment by bomanimc** [comment]
Looks like we have this (without the iframe) now on the Getting Started page https://learn.ml5js.org/#/?id=quickstart! Closing this issue for now, but please reopen if there's more we should discuss!
