### ISSUE TITLE
Merge the design of tag page and reference collective page

### ISSUE THREAD

**Issue by wenqili** [ml5js/ml5-website-archive#39]
Right now there are two different pages show a collection of a few models:
Reference page: https://ml5-website-2.netlify.com/reference/
Tag page: https://ml5-website-2.netlify.com/tags/coming-soon/

The difference is, the reference page is based on categories, tag page includes categories and special collections like `coming soon`.

I propose we merge them together to reduce the number of pages. Maybe design a system of tags or categories?

**Comment by bomanimc** [comment]
Yeah I think that this change makes sense! It looks like we don't think we support Tag pages in the current versions of the documentation site. Closing!
