### ISSUE TITLE
Raw javascript vs p5 for examples?

### ISSUE THREAD

**Issue by joeyklee** [ml5js/ml5-website-archive#44]
One thing we should consider is: do we use the p5 examples on the ml5 website? or should we include just the vanilla javascript examples? 

One thing on my todo list is to sync up the vanilla javascript examples with the p5js examples, but for now, as the p5 examples are the most extensive, we might stick with that for now?

<img width="1551" alt="Screen Shot 2019-05-15 at 14 07 56" src="https://user-images.githubusercontent.com/3622055/57798588-1617ed80-771b-11e9-8849-0e60d95f2077.png">

**Comment by shiffman** [comment]
I think others may feel differently and I might be too biased, but my preference is to focus on the p5 examples as the canonical foundation and feature those on the website! The plain JS examples can be found as extra on GitHub?

**Comment by joeyklee** [comment]
@shiffman - we can also link to the vanilla js examples on the main website, so they will be featured. I agree with you in that focusing on highlighting the p5 examples would be preferred. Because we are interacting so much with the dom, video, and images, it is really helpful to have the p5 api  so we can focus on the creative potential rather than the intricacies of interfacing with the native canvas api, etc etc.

**Comment by wenqili** [comment]
We can include both 👐
I developed the example tab as it can embed multiple examples

**Comment by bomanimc** [comment]
It looks like we landed on linking to both in the examples section of our docs, but leaning on p5.js and the useful DOM API wrappers for the code snippets.

Closing for now, but please feel free to reopen if there's additional discussion here!
