### ISSUE TITLE
website examples added list

### ISSUE THREAD

**Issue by joeyklee** [ml5js/ml5-website-archive#45]
## ml5 functions

- [ ] DCGAN()
    - [ ] example1
    - [ ] example2
- [ ] featureExtractor()
    - [x] [FeatureExtractor_Image_Classification](https://ml5js.github.io/ml5-examples/p5js/FeatureExtractor/FeatureExtractor_Image_Classification)
    - [ ] [FeatureExtractor_Image_Regression](https://ml5js.github.io/ml5-examples/p5js/FeatureExtractor/FeatureExtractor_Image_Regression)
- [ ] CVAE()
    - [ ] example1
    - [ ] example2
- [ ] KNNClassifier()
    - [ ] [KNNClassification_VideoSound](https://ml5js.github.io/ml5-examples/p5js/KNNClassification/KNNClassification_VideoSound)
    - [x] [KNNClassification_Video](https://ml5js.github.io/ml5-examples/p5js/KNNClassification/KNNClassification_Video)
    - [ ] [KNNClassification_PoseNet](https://ml5js.github.io/ml5-examples/p5js/KNNClassification/KNNClassification_PoseNet)
    - [ ] [KNNClassification_VideoSquare](https://ml5js.github.io/ml5-examples/p5js/KNNClassification/KNNClassification_VideoSquare)
- [ ] pitchDetection()
    - [ ] [PitchDetection_Game](https://ml5js.github.io/ml5-examples/p5js/PitchDetection/PitchDetection_Game)
    - [x] [PitchDetection](https://ml5js.github.io/ml5-examples/p5js/PitchDetection/PitchDetection)
- [ ] styleTransfer()
    - [ ] [StyleTransfer_Video](https://ml5js.github.io/ml5-examples/p5js/StyleTransfer/StyleTransfer_Video)
    - [x] [StyleTransfer_Image](https://ml5js.github.io/ml5-examples/p5js/StyleTransfer/StyleTransfer_Image)
- [ ] UNET()
    - [ ] example1
    - [ ] example2
- [X] word2vec()
    - [X] [Word2Vec](https://ml5js.github.io/ml5-examples/p5js/Word2Vec)
- [ ] CharRNN()
    - [ ] [CharRNN_Interactive](https://ml5js.github.io/ml5-examples/p5js/CharRNN/CharRNN_Interactive)
    - [X] [CharRNN_Text](https://ml5js.github.io/ml5-examples/p5js/CharRNN/CharRNN_Text)
    - [ ] [CharRNN_Text_Stateful](https://ml5js.github.io/ml5-examples/p5js/CharRNN/CharRNN_Text_Stateful)
- [ ] example()
    - [ ] example1
    - [ ] example2
- [ ] poseNet()
    - [X] PoseNet example on image with single detection
    - [X] ePoseNet example using p5.js with webcam
- [ ] YOLO()
    - [X] YOLO image detection on single image
    - [ ] [YOLO_webcam](https://ml5js.github.io/ml5-examples/p5js/YOLO/YOLO_webcam)
- [ ] pix2pix()
    - [X] [Pix2Pix_callback](https://ml5js.github.io/ml5-examples/p5js/Pix2Pix/Pix2Pix_callback)
    - [ ] [Pix2Pix_promise](https://ml5js.github.io/ml5-examples/p5js/Pix2Pix/Pix2Pix_promise)
- [ ] SketchRNN()
    - [X] [SketchRNN_basic](https://ml5js.github.io/ml5-examples/p5js/SketchRNN/SketchRNN_basic)
    - [ ] [SketchRNN_interactive](https://ml5js.github.io/ml5-examples/p5js/SketchRNN/SketchRNN_interactive)
- [ ] imageClassifier()
    - [x] [ImageClassification](https://ml5js.github.io/ml5-examples/p5js/ImageClassification/ImageClassification)
    - [x] [ImageClassification_Video](https://ml5js.github.io/ml5-examples/p5js/ImageClassification/ImageClassification_Video)
    - [ ] [ImageClassification_VideoScavengerHunt](https://ml5js.github.io/ml5-examples/p5js/ImageClassification/ImageClassification_VideoScavengerHunt)
    - [ ] [ImageClassification_VideoSoundTranslate](https://ml5js.github.io/ml5-examples/p5js/ImageClassification/ImageClassification_VideoSoundTranslate)
    - [ ] [ImageClassification_VideoSound](https://ml5js.github.io/ml5-examples/p5js/ImageClassification/ImageClassification_VideoSound)
     - [ ] [ImageClassification_MultipleImages](https://ml5js.github.io/ml5-examples/p5js/ImageClassification/ImageClassification_MultipleImages)

**Comment by bomanimc** [comment]
All of our examples in the codebase are now stored in ml5-library and are available on examples.ml5js.org!
