### ISSUE TITLE
iframe of GitHub page is not loaded because of http embed

### ISSUE THREAD

**Issue by wenqili** [ml5js/ml5-website-archive#49]
error message:

> Mixed Content: The page at 'https://ml5-website-2.netlify.com/reference/api-KNNClassifier/' was loaded over HTTPS, but requested an insecure resource 'http://ml5js.github.io/ml5-examples/p5js/KNNClassification/KNNClassification_Video/'. This request has been blocked; the content must be served over HTTPS.

A quick solution for this is to use Netlify host the page.

**Comment by bomanimc** [comment]
We no longer support iframes in the documentation (for anything besides Youtube Videos), so I'm closing this issue for now! We actually do host on Netlify now, though!
