### ISSUE TITLE
GraphQL image must not have selection issue

### ISSUE THREAD

**Issue by joeyklee** [ml5js/ml5-website-archive#5]
Related to: https://github.com/gatsbyjs/gatsby/issues/4123

Occurs after changing the "Team" image on the home page. (currently working on fixing & will report back on fixes)

```js
error GraphQL Error Field "image" must not have a selection since type "String" has no subfields.

  file: /Users/joeyklee/Cosmos/src/github/ml5-src/ml5-website-2/src/templates/home-page.js

  46 |                   ...GatsbyImageSharpFluid
  47 |                 }
  48 |               }
  49 |             }
  50 |             text
  51 |           }
  52 |           heading
  53 |           description
  54 |         }
  55 |         team {
> 56 |           image {
     |                 ^
  57 |             childImageSharp {
  58 |               fluid(maxWidth: 240, quality: 64) {
  59 |                 ...GatsbyImageSharpFluid
  60 |               }
  61 |             }
  62 |           }
  63 |           heading
  64 |           profile
  65 |         }
  66 |       }
```

**Comment by joeyklee** [comment]
Ah - need to run `yarn start` for developing rather than `npm run start` - closing issue!

**Comment by joeyklee** [comment]
Reopening this issue as it is persisting when changing images on the home page - specifically the Team section. 

NOTE: need to document:
1. where images need to be placed in the project scaffold - is it public or static? 
2. how to specify the path to the images.

**Comment by joeyklee** [comment]
Ah-ha! I see this noted here: https://github.com/ml5js/ml5-website-2#assets

Apologies for missing this in the docs!

**Comment by wenqili** [comment]
This issue usually means that the embed URL to images is not right.
`NPM start` should work. Still the same error after correct the URL?

**Comment by joeyklee** [comment]
@wenqili - All good now! I just needed to place the images in the correct directory:

`~/ml5-website-2/docs/assets/`

+ I haven't tested yet with an external URL, but will be sure to look into the PreviewCompatibleImage.js component to make sure the tests pass

**Comment by wenqili** [comment]
> @wenqili - All good now! I just needed to place the images in the correct directory:
> 
> `~/ml5-website-2/docs/assets/`
> 
> * I haven't tested yet with an external URL, but will be sure to look into the PreviewCompatibleImage.js component to make sure the tests pass

I don't think external link will work here, since the image will pass through the imagesharp process. I can add an alternative option here to display external images. Like the way I did for the community post.
