### ISSUE TITLE
Style code area 

### ISSUE THREAD

**Issue by joeyklee** [ml5js/ml5-website-archive#6]
Need to update syntax highlighting and code area background:

Brown is not in design specs

<img width="1408" alt="Screen Shot 2019-05-08 at 13 47 39" src="https://user-images.githubusercontent.com/3622055/57396230-f1120080-7197-11e9-960e-3486fa484e65.png">

**Comment by wenqili** [comment]
Right now the site is using two kinds of syntax highlighting themes. 
One is customized, the other one is polarized-light. 
The customized one only covers part of JavaScript syntax tho...

**Comment by shiffman** [comment]
This reminded me that we should check color contrast of the syntax highlighting (see #12).

**Comment by joeyklee** [comment]
Looks great! 
<img width="1527" alt="Screen Shot 2019-05-13 at 13 38 41" src="https://user-images.githubusercontent.com/3622055/57642045-758fc500-7584-11e9-83eb-beb1fbfc75bf.png">
