### ISSUE TITLE
web editor links

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-website-archive#68]
It would be nice for the examples tab to include a link to the p5 web editor version of the example (if there is a working one). This could go under "Source" or perhaps better yet as a link right under the iFrame running the example?'

This leads me to wonder if the code snippet is necessary? It's nice to see it there, but would the simplification of just having links to the source under the running example be worth it?

<img width="954" alt="Screen Shot 2019-05-23 at 1 05 51 PM" src="https://user-images.githubusercontent.com/191758/58272113-c14c2680-7d5b-11e9-8757-0b944b51730e.png">

**Comment by joeyklee** [comment]
@shiffman  + 1 to adding links to the p5 web editor. We can add that to the YAML spec and add that to the reference page component. 

I would leave the code snippets in as they serve as a nice and quick reference to syntax that is handy for people who use ml5.js more frequently and might be in need of a reminder of what the functions look like in context w/out having to go to the editor or redirect to github.

**Comment by bomanimc** [comment]
It looks like we don't use iframes in our current structure, so closing this issue for now! Please feel free to reopen if I'm mistaken!
