### ISSUE TITLE
Homepage background image - should communicate ml5 more clearly

### ISSUE THREAD

**Issue by joeyklee** [ml5js/ml5-website-archive#7]
The current design of the main landing page view is a highlighted project. I would opt for something more specifically communicating to our audience that people have arrived at the ml5 website. At the moment, it feels too much like people are landing on the project page of the featured project since there is no reference to ml5 in the text and the background image is so dominant. 

## Current design 

<img width="1169" alt="Screen Shot 2019-05-08 at 13 52 09" src="https://user-images.githubusercontent.com/3622055/57396491-80b7af00-7198-11e9-9ceb-6026712d4352.png">

## Interim solution / Proposed change towards something like...

see: https://github.com/ml5js/ml5-website-2/tree/homepage-updates

![Screenshot_2019-05-08 ml5js·Friendly Machine Learning For The Web(3)](https://user-images.githubusercontent.com/3622055/57396454-709fcf80-7198-11e9-9e24-9f8a694debb1.png)

## ideal solution:

We can have a ML5 sketch running in the background.. maybe something like sketchRnn?

**Comment by shiffman** [comment]
Yes, I love the idea of featuring a project made with ml5 on the homepage but I agree right now it's too much and it feels more like I've arrived at the "Let's Read a Story" page.

I love "neighborly" so much! Hah.

**Comment by joeyklee** [comment]
Another thought on this would be to add a video montage to run in the background for large/med screens and then an image for small screens, similar to the setup here:

http://selfdriving.moovellab.com/

This might help us to:
+ showcase the various functions and projects made with ml5
+ avoid issues with running unnessary heavy computation on page load
+ give the landing page a bit more dynamism

We could collect a few screen recordings and videos of ml5 projects as well as people interacting with things like posenet or some snippets of coding train an other events?

**Comment by shiffman** [comment]
I like this idea! However, I worry about the work involved with producing/creating a video. I really love the "Discover the creative possiblities of machine learning!" section and I wonder if this could be featured more up top in this area?

**Comment by bomanimc** [comment]
I think we landed on a solid, clear statis here! Further improvements could be considered through the website redesign project (#118). Closing for now!
