### ISSUE TITLE
Getting Started "move onto next section"

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-website-archive#70]
> Now that you've got a ml5.js project setup, move on to the next section to see ml5.js in action.

The above sentence at the bottom of the Quickstart page feels off. I was expecting to be able to click on it as a link. But then is each page going to link to the "next one"? They aren't really sequenced. Duplicate the left nav and list some options to "move onto?"  

All in all, I think maybe I would just remove it for simplicity right now? Or better yet, maybe just a note about the FAQ?

**Comment by joeyklee** [comment]
@shiffman - that's fine for me. I will remove that piece. I've changed "image classification" to "hello ml5" 

<img width="1149" alt="Screen Shot 2019-05-23 at 13 36 22" src="https://user-images.githubusercontent.com/3622055/58273981-d75be600-7d5f-11e9-98e2-86d3f7889cc4.png">
