### ISSUE TITLE
Documentation should give users options to start a simple webserver

### ISSUE THREAD

**Issue by hx2A** [ml5js/ml5-website-archive#76]
On the QuickStart page, we tell users to "open up that file in your web browser" but if they do so by double-clicking on it, which they are most likely to do, some of the examples won't work correctly (such as the Hello ml5 example on the next page).

Somewhere in the site we should mention that the user should be using something like `python -m http.server` to serve the page. Is Python the most user-friendly option? What about people with Windows who might not have Python on their path?

**Comment by hx2A** [comment]
This will help the Python-Windows issue:

https://mail.python.org/pipermail/python-dev/2019-May/157586.html
https://devblogs.microsoft.com/python/python-in-the-windows-10-may-2019-update/

With this feature we can easily explain how to start a simple webserver for any OS.

**Comment by joeyklee** [comment]
@hx2A - yes! Thanks for these links. 

I've personally switched to using the node.js `http-server` npm package: https://www.npmjs.com/package/http-server

Once node.js is installed, it is as easy as:

+ install the thing
```
npm install -g http-server
```

+ run the server

```
cd /to/the/folder/and/files/you/want/to/serve
http-server
```

In any case, we definitely should note the options for ml5 users :)

**Comment by shiffman** [comment]
Indeed, I also cover it in this video in case it's helpful!  https://youtu.be/FjWbUK2HdCo?list=PLRqwX-V7Uu6Zu_uqEA6NqhLzKLACwU74X

**Comment by hx2A** [comment]
Definitely helpful! We can include that in the documentation. And it looks I did not make the best choice when I ran `sudo npm install` last week. :-)

**Comment by joeyklee** [comment]
@hx2A - I've started adding notes here: https://ml5js.org/getting-started/running-examples/

**Comment by hx2A** [comment]
Great. Our documentation should also mention something about valid port numbers. Since the port number should be in the range of 1024 to 65535, beginners will get a strange error if they were to randomly pick a number like 500.

Today and tomorrow I'm busy with camp stuff and I'll continue working on this later in the week.

**Comment by bomanimc** [comment]
We now also support `npm run develop`, which will automatically start a page that hosts the examples and a locally-built version of the core library, both with live/hot-reloading! 

Thanks for this suggestion; it definitely influenced our direction!
