### ISSUE TITLE
website-2 is now the website!

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-website-archive#85]
I think we could probably archive [https://github.com/ml5js/ml5-website](ml5-website) and pin this repo as the main one! No hurry on this, let me know @joeyklee what you think the best process is.

**Comment by joeyklee** [comment]
@shiffman - yep! I will archive the `ml5-website` - website-2 is already pinned ;)

**Comment by shiffman** [comment]
Should we also rename the repos? This can be `ml5-website` and the other `ml5-website-0.1.0-archived`?

**Comment by joeyklee** [comment]
@shiffman - Yes that'd be great. Except let's wait until after EyeO?

**Comment by joeyklee** [comment]
@wenqili - Just revisiting this now. If we update the name of this repo `ml5-website-2` to `ml5-website` do we need to make sure netlify is all updated as well? Also feel free to make these changes directly. Thanks!

**Comment by wenqili** [comment]
@shiffman @joeyklee I changed the name of this repo and netlify setting to `ml5-website`. Here are all the details that are updated:
Repo name: `ml5-website`
Repo link: `https://github.com/ml5js/ml5-website`
Netlify default domain: `ml5-website.netlify.com`

**Comment by jasikpark** [comment]
This is done, no? :P

**Comment by bomanimc** [comment]
Looks like we're good to go here; closing!
