### ISSUE TITLE
Add all contributors to ml5-website-2 repo

### ISSUE THREAD

**Issue by joeyklee** [ml5js/ml5-website-archive#89]

**Comment by joeyklee** [comment]
@all-contributors please add @shiffman for content code

**Comment by joeyklee** [comment]
@all-contributors please add @wenqili for content code infra maintenance ideas

**Comment by joeyklee** [comment]
@all-contributors please add @garym140 for design

**Comment by joeyklee** [comment]
@all-contributors please add @nicoleflloyd for design

**Comment by joeyklee** [comment]
@all-contributors please add @AbolTaabol for design

**Comment by joeyklee** [comment]
@all-contributors please add @joeyklee for design code maintenance

**Comment by joeyklee** [comment]
@all-contributors please add @hx2A for content maintenance ideas

**Comment by bomanimc** [comment]
Looks like this has been addressed!
