### ISSUE TITLE
Match domain of new website to ml5js.org when ready

### ISSUE THREAD

**Issue by joeyklee** [ml5js/ml5-website-archive#9]
## Todos

When we're ready to launch:

- [x] get logins for domain name service ==> @shiffman  has the keys! :) 
- [x] add domain name to `ml5-website-2` repo
- [x] test!

**Comment by shiffman** [comment]
I've got the keys to ml5js.org!

**Comment by joeyklee** [comment]
Super - thanks @shiffman ! I'll DM you for the info :) Thank you!

**Comment by wenqili** [comment]
- [ ] accessibility audit, #12 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joeyklee** [comment]
@wenqili - Hi! I hope you're well! 

Quick things we'd like to do:
1. Change the domain name over asap
2. Move the netflify account to an ml5 email address if possible 

Even though the site isn't 100% finished, it is more current than the other website and it is at a stage where it is ok to show. It'd be better to start testing this week before Eyeo! 

Let @shiffman and me know if this is possible. Thanks!

**Comment by wenqili** [comment]
Move the discussion to slack.
Update: I added the domain to Netlify, waiting for the domain holder to add DNS to the domain.

For the ownership, reference here:
https://www.netlify.com/docs/teams/#transfer-sites-between-teams

Please send me an email address that will be associated with the site. Thanks!

**Comment by joeyklee** [comment]
Done! Closing this now :) 

## What we learned

+ definitely change domains  >2 days before your launch :) 
+ for switching to netlify, you just need to change your CNAME in your domain name provider and point it to the netlify address

```markdown

| type | name | value | TTL |
| ---- | ---- | ---- | ---- |
| A     | @ | `###.###.##.###` | 1 hour |
| CNAME    | www | `superawesomesite.netlify.com` | 1 hour |

```
